const mongoose = require("mongoose");

const perfilEgresadoSchema = new mongoose.Schema({
  firebaseUid: { type: String, required: true, unique: true }, // Firebase UID
  nombreCompleto: { type: String, required: true },
  anioEgreso: { type: Number, required: true },
  carrera: {
    type: String,
    required: true,
    enum: [
      "Administración y Gerencia",
      "Administración de Negocios Globales",
      "Arquitectura",
      "Biología",
      "Contabilidad y Finanzas",
      "Derecho y Ciencia Política",
      "Economía",
      "Ingeniería Civil",
      "Ingeniería Electrónica",
      "Ingeniería Industrial",
      "Ingeniería Informática",
      "Ingeniería Mecatrónica",
      "Marketing Global y Administración Comercial",
      "Medicina Humana",
      "Medicina Veterinaria",
      "Psicología",
      "Traducción e Interpretación",
      "Turismo, Hotelería y Gastronomía",
    ],
  },
  gradoAcademico: {
    type: String,
    enum: ["Bachiller", "Titulado", "Magíster", "Doctorado"],
  },
  experienciaLaboral: {
    aniosExperiencia: {
      type: String,
      enum: ["0–1 años", "2–3 años", "4–5 años", "Más de 5 años"],
    },
    areasExperiencia: [
      {
        type: String,
        enum: [
          "Finanzas",
          "Marketing",
          "Desarrollo de software",
          "Recursos Humanos",
          "Logística",
          "Atención al cliente",
          "Legal",
          "Educación",
        ],
      },
    ],
    tipoEmpresa: {
      type: String,
      enum: ["Pública", "Privada", "ONG", "Startup", "Multinacional"],
    },
  },
  interesesProfesionales: {
    areasInteres: [
      {
        type: String,
        enum: [
          "Innovación y tecnología",
          "Gestión empresarial",
          "Comercio exterior",
          "Educación y formación",
          "Emprendimiento",
          "Proyectos sociales",
        ],
      },
    ],
    modalidad: {
      type: String,
      enum: ["Presencial", "Remoto", "Híbrido"],
    },
    tipoJornada: {
      type: String,
      enum: ["Tiempo completo", "Medio tiempo", "Freelance"],
    },
  },
  habilidades: {
    idiomas: [
      {
        idioma: {
          type: String,
          enum: [
            "Español",
            "Inglés",
            "Portugués",
            "Frances",
            "Italiano",
            "Alemán",
            "Chino",
            "Japonés",
            "Ruso",
          ],
        },
        nivel: {
          type: String,
          enum: ["Básico", "Intermedio", "Avanzado"],
        },
      },
    ],
  },
  ubicacion: {
    distritoResidencia: {
      type: String,
      required: true,
      enum: [
        "Ancón",
        "Ate",
        "Barranco",
        "Breña",
        "Carabayllo",
        "Cercado de Lima",
        "Chaclacayo",
        "Chorrillos",
        "Cieneguilla",
        "Comas",
        "El Agustino",
        "Independencia",
        "Jesús María",
        "La Molina",
        "La Victoria",
        "Lince",
        "Los Olivos",
        "Lurigancho",
        "Lurín",
        "Magdalena del Mar",
        "Miraflores",
        "Pachacámac",
        "Pucusana",
        "Pueblo Libre",
        "Puente Piedra",
        "Punta Hermosa",
        "Punta Negra",
        "Rímac",
        "San Bartolo",
        "San Borja",
        "San Isidro",
        "San Juan de Lurigancho",
        "San Juan de Miraflores",
        "San Luis",
        "San Martín de Porres",
        "San Miguel",
        "Santa Anita",
        "Santa María del Mar",
        "Santa Rosa",
        "Santiago de Surco",
        "Surquillo",
        "Villa El Salvador",
        "Villa María del Triunfo",
      ],
    },
    disponibilidadReubicacion: { type: Boolean },
    disponibilidadViajar: { type: Boolean },
  },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("PerfilEgresado", perfilEgresadoSchema);
